# Generated by Django 4.2.5 on 2024-02-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('active', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['department_name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insitution_name', models.CharField(max_length=200)),
                ('insitution_campus', models.CharField(max_length=200)),
                ('insitution_email', models.CharField(max_length=100)),
                ('insitution_postbox', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['insitution_name', 'insitution_campus'],
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeknum', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('closed', models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kengen.attsession')),
            ],
            options={
                'ordering': ['weeknum', 'session'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_photo', models.ImageField(default='user.svg', upload_to='supervisir')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kengen.department')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kengen.attsession')),
                ('supervisor_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kengen.department')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kengen.institution')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Kengen.attsession')),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityDone', models.TextField(default='', max_length=2000)),
                ('newSkillsAquired', models.TextField(default='', max_length=2000)),
                ('challangesMet', models.TextField(default='', max_length=2000)),
                ('approved', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('student_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kengen.student')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Kengen.week')),
            ],
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
